project:
  type: website

website:
  title: "FdR"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/fderyckel
      - icon: twitter
        href: https://twitter.com/Read_The_Dung
format:
  html:
    theme: journal
    css: styles.css

editor: visual

